baseURL = 'http://175.27.130.124'
languageCode = 'en-us'
title = 'NJU AI 通识课'
theme = "njuai"
[outputs]
  home = ["HTML", "RSS", "JSON"]

[taxonomies]
  modality = "modality"
  availability = "availability"
  scenario = "scenario"

[pagination]
  disableAliases = false
  pagerSize = 12